### ISSUE TITLE
Fungerar inte längre

### ISSUE THREAD

**Issue by ZetaTwo** [eringh/Sangbok#2]
Har fått rapport om att appen inte fungerar.
Har inte Android så jag kan inte testa.

**Comment by eringh** [comment]
Jag vet... Någon har flyttat från från "http://" till "https://", kan det vara du kanske?   ;)
Funkar om man manuellt ändrar adressen i inställningar, men jag borde fixa det. Ska försöka ordna det.

**Comment by ZetaTwo** [comment]
Grymt! Yes. Jag har fixat HTTPS åt sektionen. Måste samtidigt reda ut vart signeringsnycklarna har tagit vägen. :P

**Comment by eringh** [comment]
Nu har jag uppdaterat det! Default är nu https.
